### ISSUE TITLE
APK build failure on openSUSE Tumbleweed and Debian Buster

### ISSUE THREAD

**Issue by lpechacek** [OpenOrienteering/superbuild#36]
Not sure this is caused by Superbuild but I'm recording my trouble here so that others can follow up.

Trying to build Android APK results in the following error.
```
...
Scanning dependencies of target qtbase-5.6.2-arm-linux-androideabi
[ 35%] Generating configuration for qtbase-5.6.2-arm-linux-androideabi
-- Generating qtbase-5.6.2 for system arm-linux-androideabi
-- Configuring done
CMake Error at CMakeLists.txt:32 (file):
  Error evaluating generator expression:

    $<${crosscompiling}:
        $<${windows}:
          mkdir -p "${SOURCE_DIR}/mkspecs/win32-g++-${SYSTEM_NAME}"
          COMMAND cp "${SOURCE_DIR}/mkspecs/win32-g++/qmake.conf" "${SOURCE_DIR}/mkspecs/win32-g++-${SYSTEM_NAME}/"
          COMMAND cp "${SOURCE_DIR}/mkspecs/win32-g++/qplatformdefs.h" "${SOURCE_DIR}/mkspecs/win32-g++-${SYSTEM_NAME}/"
          COMMAND sed -i -f "qmake_conf_changes.sed" "${SOURCE_DIR}/mkspecs/win32-g++-${SYSTEM_NAME}/qmake.conf"
        >
        $<${android}:
          mkdir -p "${SOURCE_DIR}/mkspecs/android-g++-${SYSTEM_NAME}"
          COMMAND cp "${SOURCE_DIR}/mkspecs/android-g++/qmake.conf" "${SOURCE_DIR}/mkspecs/android-g++-${SYSTEM_NAME}/"
          COMMAND cp "${SOURCE_DIR}/mkspecs/android-g++/qplatformdefs.h" "${SOURCE_DIR}/mkspecs/android-g++-${SYSTEM_NAME}/"
          COMMAND sed -i -f "qmake_conf_changes.sed" "${SOURCE_DIR}/mkspecs/android-g++-${SYSTEM_NAME}/qmake.conf"
        >
        COMMAND
         # Cf. qtbase configure "SYSTEM_VARIABLES"
         "${CMAKE_COMMAND}" -E env 
           --unset=AR
           --unset=RANLIB
           --unset=STRIP
           --unset=OBJDUMP
           --unset=LD
           --unset=CC
           --unset=CXX
           --unset=CFLAGS
           --unset=CXXFLAGS
           --unset=LDFLAGS
           # fall through
      >

  Expression did not evaluate to a known generator expression


-- Generating done
-- Build files have been written to: /data/build/android-build/arm-linux-androideabi/qtbase-5.6.2/tmp.superbuild/config/generator
make[3]: *** [CMakeFiles/qtbase-5.6.2-arm-linux-androideabi.dir/build.make:67: arm-linux-androideabi/qtbase-5.6.2/tmp.superbuild/CMakeLists.txt] Error 1
make[3]: *** Deleting file 'arm-linux-androideabi/qtbase-5.6.2/tmp.superbuild/CMakeLists.txt'
make[2]: *** [CMakeFiles/Makefile2:1797: CMakeFiles/qtbase-5.6.2-arm-linux-androideabi.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:4946: CMakeFiles/openorienteering-mapper-master-arm-linux-androideabi-package.dir/rule] Error 2
make: *** [Makefile:1990: openorienteering-mapper-master-arm-linux-androideabi-package] Error 2
lpechacek@fmn:/data/build/android-build> 
```
There has been various trouble with Superbuild on Tumbleweed but this one is completely new.

Steps to reproduce:
1) `cmake -D ENABLE_arm-linux-androideabi:BOOL=ON /data/src/superbuild/`
2) `make openorienteering-mapper-master-arm-linux-androideabi-package`

On Debian Buster JAVA_HOME has to point to OpenJDK 8 so that Android sdk_manager works.

Superbuild version: v20190622.4
Mapper-master version: 88576a0784c7079f4a94cc9c47207ee16741908f

**Comment by dg0yt** [comment]
You probably want to use openorienteering-mapper-*git*-master.

openorienteering-mapper-master and qt-5.6 are more or less bit-rot. I only left qt-5.6 because it is still referred to by openorienteering-mapper-0.8.4 which will eventually become 0.9.0. openorienteering-mapper-master is 0.8's old companion, now waiting for retirement.

**Comment by lpechacek** [comment]
Indeed. Thanks for the hint, Kai! Now I managed to build `openorienteering-mapper-git-dev-arm-linux-androideabi-package` while `master` failed build while trying to search for a Proj4 directory.

Is `openorienteering-mapper-git-master-arm-linux-androideabi-package` supposed to build or shall I leave it as is?

**Comment by dg0yt** [comment]
> Is openorienteering-mapper-git-master-arm-linux-androideabi-package supposed to build or shall I leave it as is?

It may be left as is until we release 0.9.0 which becomes master a that time.
For builds of the Mapper master branch, it is probably easier to start from Superbuild 5f342c84, i.e. the state when we released v0.8.4.

**Comment by lpechacek** [comment]
Let's close this one. The lesson learned is that Superbuild status must match Mapper source code status. As long as I keep these two in sync, I'm able to produce working APK's. Thanks!

**Comment by dg0yt** [comment]
Well, this reminds me to do the post-v0.9.0 cleanup... 
- The Mapper v0.9.0 release was build from the cmake script which is in the `ci` folder of Mapper's souce code, and the Superbuild configuration is documented in the GH release. So there is no strong requirement to have a cmake script per Mapper release in the Superbuild repository.
- I just converted CupCalculator to use Superbuild with Azure Pipelines CI, applying some simplifcations over how things are done in the Mapper repository. Instead of having complete `openorienteering-*.cmake` scripts maintained here, it is easier to have a simple script which just includes the ci cmake script from a separate source directory (git checkout). My `openorienteering-cupcalculator-dev.local.cmake` is little more than:

~~~
set(CupCalculator_CI_SOURCE_DIR "/home/dg0yt/projects/OpenOrienteering/cupcalculator" CACHE STRING "")
include("${CupCalculator_CI_SOURCE_DIR}/ci/openorienteering-cupcalculator-ci.cmake")
~~~ 

This doesn't need to be local if the include is made optional based on the existence of the file. It will always use a script which is maintained with the projects source code.
